### ISSUE TITLE
Error when trying to use responsive variants in Unframer

### ISSUE THREAD

**Issue by mrlaureto** [remorses/unframer#14]
`Error: Could not find the module "\my-app\framer\feature.js#default#Responsive" in the React Client Manifest. This is probably a bug in the React Server Components bundler.`

I'm using this tool to import various sections from Framer into my NextJS project. When I try using the Component.Responsive tag, I get this error even when the variants are appropriately named based on the configurations I have in Framer.

I am really not a developer just a designer experimenting with Framer and NextJS. 

Usage:
![image](https://github.com/remorses/unframer/assets/93614520/18ff7233-927b-498a-9627-ffbf548f4c4b)

**Comment by remorses** [comment]
Try adding “use client” at the top of the file

**Comment by mrlaureto** [comment]
It's all good now bro. Thanks so much! Rlly appreciate the tool🫡

**Comment by remorses** [comment]
Glad you like it!
