### ISSUE TITLE
Set responsive widths as props

### ISSUE THREAD

**Issue by csreyes** [remorses/unframer#15]
first and foremost, thanks so much for this project. we're building out a production-ready app using it and its made development so much easier (still bugs here and there but well worth it).

It seems like the viewport for different base, lg, md, etc is set somewhere - is it possible to allow us to define overrides these widths ? thanks so much

**Comment by remorses** [comment]
Hi, this is not currently possible, i can let users customize the breakpoints with some css variables

**Comment by remorses** [comment]
What are the other bugs you found?

**Comment by remorses** [comment]
Added section in readme

## Custom breakpoints for responsive variants

You can change the breakpoints by passing a breakpoints in your `unframer.json` config

```json
{
    "$schema": "https://unframer-schema.vercel.app/schema.json",
    "outDir": "./src/framer",
    "breakpoints": { "sm": 300, "md": 760 },
    "components": {}
}
```
