### ISSUE TITLE
Parse RGB colour error

### ISSUE THREAD

**Issue by jameshullaballu** [remorses/unframer#16]
Hi there,

I'm experiencing issues with Unframer components when they change between variable states. Specifically, I'm getting an error indicating that the components are unable to parse color properties, as shown below. This error only occurs when changing states, which causes the app to break.

While some components successfully change states without issue, others do not. For example, recreating a faulty component as variable states in an already functioning one seems to work.

I've ensured that the Framer colour tokens are included in the app's CSS, even though their values haven't changed in the project.

I would really appreciate any help in resolving this issue. Thank you!

<img width="464" alt="Screenshot 2024-08-13 at 09 52 40" src="https://github.com/user-attachments/assets/6b3172a5-8bc9-47a1-9e76-81a0bec4c3b4">

**Comment by remorses** [comment]
Can you paste the component url here?

**Comment by jameshullaballu** [comment]
Here's a revised version of your message for improved clarity and flow:

Sure, this component works correctly when switching between the first and second variables (triggered by the buttons). However, it breaks when transitioning from the third variable back to the first or second. As far as I can tell, each of these buttons (and their associated colors) are duplicates of one another.

Here’s the component I’m using:
```"GrowthSpaceMenu" : "https://framer.com/m/GrowthSpaceMenu-i06U.js",```

**Comment by remorses** [comment]
tried with the latest version of unframer 2.6.3 and it works fine, try updating

**Comment by jameshullaballu** [comment]
Ah yes thank you! I hadn't realised I was working with an older version
