### ISSUE TITLE
TypeError: motion2.create is not a function

### ISSUE THREAD

**Issue by csreyes** [remorses/unframer#17]
first off, thanks for this package :)

trying to install this component:
https://framer.com/m/LandingPage-eq39.js

running into this error:
var Variants = motion2.create(React.Fragment,);
                       ^

TypeError: motion2.create is not a function

lmk if i'm missing something, thanks!

**Comment by remorses** [comment]
I updated the unframer package, it should now work correctly if you update unframer with `npm update unframer@latest` or similar
